name: Artifact Demo

on:
  workflow_dispatch:

jobs:
  job_1:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Create a local file"
        run: echo "My name is Ankus Nayak." > file1.txt

      - uses: action/upload-artifact@v2
        with:
          name: file
          path: file1.txt
          retention-days: 10

  job_2:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: action/download-artifact@v2
        with:
          name: file
      - name: Printing the file content
        run: cat file1.txt
