
name: A Basic Workflow

# control when the workflow will run
on:

  # Triggers the workflow on push and pull request events only for the "main" branch
  # push:
  #   branches: ["main"]
  #   # branches-ignore: ["ignore"]
  #   # paths: ".github/*"

  # pull_request:
  #   branches: ["main"]

  # Allows you to run this workflow manually from Actions tab
  workflow_dispatch:


# A workflow run is made up of one of more jobs that can run sequentially or in parallel
jobs:
  # Job Name --- A job is a set of steps in a workflow that execute on the same runner. Each step is e
  build-app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other action to build,
          echo test, and deploy your project.
  
  build-api:
    runs-on: windows-latest
    steps:
      - run: echo "Building API"

  build-db:
    # A job must have atleast one step to execute
    needs: build-app
    runs-on: windows-latest
    steps:
      - run: echo "Hello Windows"

  package:
    needs: [build-app,build-db]
    runs-on: macos-latest
    steps:
      - run: echo "Hello MacOS"

  





