name: create-deployment

on:
  push:
    branches:
      - 'main'
      - 'stage'
      - 'prod'
  
jobs:
  create-deplyment:
    name: Create deployment for branch
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-name@v6

      # - name: Create Github deployment for '${{ steps.branch-name.outputs.current_branch }}'
      #   run: |
      #     echo "Name: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Create Github deployment for '${{ steps.branch-name.outputs.current_branch }}'
        uses: chrnorm/deployment-action@v2
        id: deployment
        # with:
        #   token: "${{ secrets.CI_GH_TOKEN }}"
        #   environment: ${{ steps.branch-name.outputs.current_branch }}
        #   ref: ${{ steps.branch-name.outputs.current_branch }}


